services:
  api:
    build:
      dockerfile: Dockerfile-dev-container
      context: .
    # command: tail -f /dev/null
    ports:
      - "8000:8000"
    volumes:
      - .:/workspace:cached
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 5s